title: Jonathan Lopez
description: 'Ingeniero de Sistemas'
url: ''
avatar: /avatar.jpeg
paginate: 5
permalink: pretty
cover_image: /bg.jpeg
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - scripts/
  - not-pure-poole.gemspec
twitter:
  username: vszhub
  card: summary
logo: logo.png
social:
  name: Songzi Vong
  links:
    - 'https://twitter.com/jonathanlop82'
    - 'https://github.com/jonathanlop82'
google_site_verification: xxxxx
lang: en
sass:
  sass_dir: _sass
  style: ':compressed'
author:
  name: Songzi Vong
  url: 'https://github.com/vszhub/'
  email: vszhub@gmail.com
baseurl: ''
